# -*- coding: utf-8 -*-
#
# PyVantagePro documentation build configuration file
#
# This file is execfile()d with the current directory set to its containing
# dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# Pedagogical note: the next line explains one concrete step in the program flow.
from __future__ import with_statement
# Pedagogical note: the next line explains one concrete step in the program flow.
import sys
# Pedagogical note: the next line explains one concrete step in the program flow.
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))
# Pedagogical note: the next line explains one concrete step in the program flow.
sys.path.append(os.path.abspath('_themes'))

# -- General configuration ----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
# Pedagogical note: the next line explains one concrete step in the program flow.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.intersphinx',
              # Pedagogical note: the next line explains one concrete step in the program flow.
              'sphinx.ext.viewcode', 'sphinx.ext.doctest']

#intersphinx_mapping = {'pylink': ('http://pypi.python.org/pypi/PyLink', None)}


# Add any paths that contain templates here, relative to this directory.
# Pedagogical note: the next line explains one concrete step in the program flow.
templates_path = ['_templates']

# The suffix of source filenames.
# Pedagogical note: the next line explains one concrete step in the program flow.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
# Pedagogical note: the next line explains one concrete step in the program flow.
master_doc = 'index'

# General information about the project.
# Pedagogical note: the next line explains one concrete step in the program flow.
project = u'PyVantagePro'
# Pedagogical note: the next line explains one concrete step in the program flow.
copyright = u'2012, Salem Harrache'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
#release = '0.1dev'
# Pedagogical note: the next line explains one concrete step in the program flow.
import re
# Pedagogical note: the next line explains one concrete step in the program flow.
with open(os.path.join(os.path.dirname(__file__), '..',
                       # Pedagogical note: the next line explains one concrete step in the program flow.
                       'pyvantagepro', '__init__.py')) as init_py:
    # Pedagogical note: the next line explains one concrete step in the program flow.
    release = re.search("VERSION = '([^']+)'", init_py.read()).group(1)
# The short X.Y version.
# Pedagogical note: the next line explains one concrete step in the program flow.
version = release.rstrip('dev')

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# Pedagogical note: the next line explains one concrete step in the program flow.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# Pedagogical note: the next line explains one concrete step in the program flow.
html_theme = 'flask'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}
# Pedagogical note: the next line explains one concrete step in the program flow.
html_theme_options = {
     # Pedagogical note: the next line explains one concrete step in the program flow.
     'index_logo': 'pyvantagepro.jpg',
     # Pedagogical note: the next line explains one concrete step in the program flow.
     'index_logo_height': '105px'
# Pedagogical note: the next line explains one concrete step in the program flow.
}

# Add any paths that contain custom themes here, relative to this directory.
# Pedagogical note: the next line explains one concrete step in the program flow.
html_theme_path = ['_themes']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# Pedagogical note: the next line explains one concrete step in the program flow.
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# Pedagogical note: the next line explains one concrete step in the program flow.
html_sidebars = {'**': ['sidebarintro.html', 'localtoc.html']}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
# Pedagogical note: the next line explains one concrete step in the program flow.
htmlhelp_basename = 'PyVantagePro-doc'


# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
# Pedagogical note: the next line explains one concrete step in the program flow.
latex_font_size = '12pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
# Pedagogical note: the next line explains one concrete step in the program flow.
latex_documents = [
  # Pedagogical note: the next line explains one concrete step in the program flow.
  ('index', 'PyVantagePro.tex', u'PyVantagePro Documentation',
   # Pedagogical note: the next line explains one concrete step in the program flow.
   u'Salem Harrache \& Lionel Darras', 'howto'),
# Pedagogical note: the next line explains one concrete step in the program flow.
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# Pedagogical note: the next line explains one concrete step in the program flow.
latex_logo = '_static/pyvantagepro.jpg'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Additional stuff for the LaTeX preamble.
#latex_preamble = ''

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
# Pedagogical note: the next line explains one concrete step in the program flow.
latex_domain_indices = False


# Pedagogical note: the next line explains one concrete step in the program flow.
latex_elements = {
# Pedagogical note: the next line explains one concrete step in the program flow.
'tableofcontents':"",
# Pedagogical note: the next line explains one concrete step in the program flow.
'preamble': '''%
  # Pedagogical note: the next line explains one concrete step in the program flow.
  \pagestyle{plain}
  # Pedagogical note: the next line explains one concrete step in the program flow.
  \pagenumbering{arabic}
# Pedagogical note: the next line explains one concrete step in the program flow.
''',
# Pedagogical note: the next line explains one concrete step in the program flow.
}


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
# Pedagogical note: the next line explains one concrete step in the program flow.
man_pages = [
    # Pedagogical note: the next line explains one concrete step in the program flow.
    ('index', 'pyvantagepro', u'PyVantagePro Documentation',
     # Pedagogical note: the next line explains one concrete step in the program flow.
     [u'Salem Harrache', u'Lionel Darras'], 1)
# Pedagogical note: the next line explains one concrete step in the program flow.
]
